Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end
  config.vm.provision "shell", path: "provision/install.sh"
  # cantal
  config.vm.network "forwarded_port", guest: 22682, host: 22682
  # verwalter
  config.vm.network "forwarded_port", guest: 8379, host: 8379
  # rsync
  config.vm.network "forwarded_port", guest: 873, host: 8873
  # nginx
  config.vm.network "forwarded_port", guest: 80, host: 8080
end
